version: "3.9"

services:
  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    container_name: nest-backend
    env_file:
      - ./apps/backend/.env
    ports:
      - "4000:3000"
    restart: unless-stopped

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    container_name: next-frontend
    env_file:
      - ./apps/frontend/.env
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped