packages:
  - packages/*
  - apps/*

ignoredBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@tailwindcss/oxide'
  - prisma
  - sharp

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@swc/core'
